/*
 * Copyright (c) 2008  VirtualPlane Systems, Inc.
 */
#ifndef INCLUDED_vfm_common
#define INCLUDED_vfm_common

/**
 * @file
 * @brief Common attributes for VFM resource management API.
 */

/**
 * @brief BridgeX Manager GUID
 */
typedef uint32_t vfm_guid_t;

/**
 *@brief A bitmask to identify the writable properties of a resource
 */
typedef uint32_t vfm_component_mask_t;

/**
 * @brief Layer 2 Ethernet VLAN ID
 */
typedef uint32_t vlan_id_t;

/**
 * @brief ID of a physical module
 */
typedef uint32_t vfm_io_module_t;

/**
 * @brief 48 bit MAC Addr
 */
typedef uint8_t en_mac_addr_t[6];

/**
 * @brief 64 bit IB GUID
 */
typedef uint8_t ib_guid_t[8];

/**
 * @brief 24 bit FC-ID
 */
typedef uint8_t fc_id_t[3];

/**
 * @brief Reserved resource ID
 */
enum ResourceEnumIdEnum
{
    /**
     * @brief An invalid resource ID.
     */
    VFM_INVALID_ID	= 0,
};


/**
 * @brief List of protocol types supported on VFM
 */
typedef enum
{
    /**
     * @brief Ethernet protocol
     */
    VFM_PROTOCOL_EN	= 1,

    /**
     * @brief InfiniBand protocol
     */
    VFM_PROTOCOL_IB,
    /**
     * @brief Fibre Channel protocol
     */
    VFM_PROTOCOL_FC
}
vfm_protocol_t;

/**
 * @brief A Virtual adapter ID. The vadapter identifier is generated by the
 * system such that it can uniquely identify a vadapter object on VFM. It
 * could be an auto-increment counter.
 */
typedef uint32_t vfm_vadapter_id_t;

/**
 * @brief A virtual fabric id. This is a unique identifier for the vfabric.
 * This id is unique within a VFM context and auto-generated by the
 * system.
 */
typedef uint32_t vfm_vfabric_id_t;

/**
 * @brief A Gateway module Identifier.
 * This id is unique within a VFM context and auto-generated by the system. 
 */
typedef uint32_t vfm_gw_module_id_t;
typedef uint32_t vfm_gw_id_t;

/**
 * @brief Bridge device GUID.
 * VFM queries the GUID from the BridgeX device during initialization. The
 * bridge GUID are globally unique.
 */
typedef uint64_t vfm_bd_guid_t;

/**
 * @brief A gateway module physical index. This is a identifier for the porti
 * derived from the physical configuration of the bridge device. 
 */
typedef char *vfm_gw_module_index_t;
#endif /* INCLUDED_vfm_common */
